### ISSUE TITLE
relative import should know it's own relative imports

### ISSUE THREAD

**Issue by Lordluen** [pcattori/require-py#12]
If I import a relative file:
`foo = require('../../scripts/bar/test.py')`
and `test.py` imports another file that is in `../../scripts/bar`, this will fail. It feels like it should not.

**Comment by pcattori** [comment]
@Lordluen how are you importing `../../scripts/bar` in `test.py`? via `require` or through some other mechanism? What error do you get?

if you could outline a directory structure and file contents for a minimal example, I can reproduce and address this

**Comment by Lordluen** [comment]
If you try the README demo, but add a file called `meh.py` in the `bar-directory`. Add a function to meh.py and reference it in bar.py. Such that:
bar-directory/meh.py:
```
def hello_world():
    print('Hello World')
    return
```
bar-directory/bar.py:
```
import meh

def hello():
    meh.hello_world()
    return
```
foo-directory/foo.py:
```
from require import require
bar = require('../bar-directory/bar.py')

bar.hello()
```

The error is:
```
pecked$ python foo.py 
Traceback (most recent call last):
  File "foo.py", line 2, in <module>
    bar = require('../bar-directory/bar.py')
  File "/opt/upgrade_element/venv/lib/python2.7/site-packages/require/require.py", line 102, in require
    return load_py2_module_at(absolute_path)
  File "/opt/upgrade_element/venv/lib/python2.7/site-packages/require/require.py", line 55, in load_py2_module_at
    return imp.load_module(os.path.splitext(absolute_path)[0], *spec)
  File "/home/pecked/require_test/bar-directory/bar.py", line 1, in <module>
    import meh
ImportError: No module named meh
```

**Comment by pcattori** [comment]
relevant: http://stackoverflow.com/questions/41861427/python-how-to-import-a-module-given-the-full-path-in-the-presence-of-implicit

**Comment by pcattori** [comment]
The solution is not to write `import meh` as this implicitly imports a sibling file. Instead explicitly import `meh` via `require`: `meh = require('./meh.py')`
