### ISSUE TITLE
Issue with Conda?

### ISSUE THREAD

**Issue by Lordluen** [pcattori/require-py#13]
I attempted to install require with pip in a conda environment. Then I tried the readme demo and this is what I get:
```
pecked$ python foo.py
Traceback (most recent call last):
  File "foo.py", line 2, in <module>
    bar = require('../bar-directory/bar.py')
  File "/Users/pecked/anaconda/lib/python2.7/site-packages/require/__init__.py", line 177, in require
    export = Export.load(requirement)
  File "/Users/pecked/anaconda/lib/python2.7/site-packages/require/__init__.py", line 113, in load
    module, export = requirement.split(':', 1)
ValueError: need more than 1 value to unpack
```
Not sure what that is about.

**Comment by Lordluen** [comment]
I should note this does not happen when I install in a virtualenv.

**Comment by pcattori** [comment]
Looks like this might be a name conflict. Seems like `anaconda` also has a package called `require`, so its using that rather than this code base.

I bet `/Users/pecked/anaconda/lib/python2.7/site-packages/require/__init__.py` is a `anaconda`-related file, not a `require.py`-related file
